server:
  port: 8090
spring:
  redis:
    host: 10.200.6.166
#    host: 127.0.0.1
#    port: 6378
    port: 6379
    database: 11
    
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    password: 'goldcardiot'
  output:
    ansi:
      enabled: always
